In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('sample_data.csv')
data

,ID,Segment,Country,Product,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Profit,Date
0,entry-1,Government,Canada,Carretera,1618.5,3.0,20.0,"$32,370.00","$16,185.00",2014-01-01
1,entry-2,Government,Germany,Carretera,1321.0,3.0,20.0,"$26,420.00","$13,210.00",2014-01-01
2,entry-3,Midmarket,France,Carretera,2178.0,3.0,15.0,"$32,670.00","$10,890.00",2014-06-01
3,entry-4,Midmarket,Germany,Carretera,888.0,3.0,15.0,"$13,320.00","$4,440.00",2014-06-01
4,entry-5,Midmarket,Mexico,Carretera,2470.0,3.0,15.0,"$37,050.00","$12,350.00",2014-06-01
...,...,...,...,...,...,...,...,...,...,...
695,entry-696,Small Business,France,Amarilla,2475.0,260.0,300.0,"$7,42,500.00","$12,375.00",2014-03-01
696,entry-697,Small Business,Mexico,Amarilla,546.0,260.0,300.0,"$1,63,800.00","$2,730.00",2014-10-01
697,entry-698,Government,Mexico,Montana,1368.0,5.0,7.0,"$9,576.00","$1,299.60",2014-02-01
698,entry-699,Government,Canada,Paseo,723.0,10.0,7.0,"$5,061.00",$686.85,2014-04-01
699,entry-700,Channel Partners,United States of America,VTT,1806.0,250.0,12.0,"$21,672.00","$13,003.20",2014-05-01

In [3]:
print(data['Country'])

0                        Canada
1                       Germany
2                        France
3                       Germany
4                        Mexico
                 ...
695                      France
696                      Mexico
697                      Mexico
698                      Canada
699    United States of America
Name: Country, Length: 700, dtype: object